import os
import re
import sqlite3

import psycopg2
from psycopg2.extras import RealDictCursor
from werkzeug.security import generate_password_hash


DATABASE = "class_finance.db"


class PostgreSQLConnection:
    def __init__(self, connection):
        self.connection = connection

    def execute(self, sql, params=()):
        sql = sql.strip()

        sql = re.sub(
            r"^INSERT\s+OR\s+IGNORE\s+INTO",
            "INSERT INTO",
            sql,
            flags=re.IGNORECASE
        )

        if "INSERT INTO" in sql.upper() and "ON CONFLICT" not in sql.upper():
            if sql.upper().startswith("INSERT INTO"):
                sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"

        sql = sql.replace("?", "%s")

        cursor = self.connection.cursor()
        cursor.execute(sql, params)
        return cursor

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()

    def close(self):
        self.connection.close()


def get_connection():
    database_url = os.environ.get("DATABASE_URL")

    if database_url:
        connection = psycopg2.connect(
            database_url,
            cursor_factory=RealDictCursor
        )
        return PostgreSQLConnection(connection)

    connection = sqlite3.connect(DATABASE)
    connection.row_factory = sqlite3.Row
    return connection


def initialize_database():
    connection = get_connection()

    is_postgresql = isinstance(connection, PostgreSQLConnection)

    if is_postgresql:
        id_type = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        amount_type = "DOUBLE PRECISION"
    else:
        id_type = "INTEGER PRIMARY KEY AUTOINCREMENT"
        amount_type = "REAL"

    connection.execute(f"""
        CREATE TABLE IF NOT EXISTS students (
            id {id_type},
            matric_number TEXT NOT NULL UNIQUE,
            full_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'Active',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    connection.execute(f"""
        CREATE TABLE IF NOT EXISTS payments (
            id {id_type},
            student_id INTEGER NOT NULL,
            amount {amount_type} NOT NULL,
            purpose TEXT,
            payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            receipt_reference TEXT,
            receipt_file TEXT,
            status TEXT NOT NULL DEFAULT 'Pending',
            verification_note TEXT,
            verified_by TEXT,
            verified_at TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            ocr_text TEXT,
            ocr_amount {amount_type},
            ocr_date TEXT,
            ocr_reference TEXT,
            ocr_sender TEXT,
            ocr_recipient TEXT,
            ocr_narration TEXT,
            ai_verification TEXT,
            ai_verification_note TEXT,

            FOREIGN KEY (student_id)
                REFERENCES students(id)
        )
    """)

    connection.execute(f"""
        CREATE TABLE IF NOT EXISTS payment_purposes (
            id {id_type},
            name TEXT NOT NULL UNIQUE,
            expected_amount {amount_type} NOT NULL,
            status TEXT NOT NULL DEFAULT 'Active',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    connection.execute(f"""
        CREATE TABLE IF NOT EXISTS admins (
            id {id_type},
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            full_name TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'Active',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    for i in range(1, 8):
        username = os.environ.get(f"ADMIN_BOOTSTRAP_USERNAME_{i}")
        full_name = os.environ.get(f"ADMIN_BOOTSTRAP_NAME_{i}")
        password = os.environ.get(f"ADMIN_BOOTSTRAP_PASSWORD_{i}")

        if username and full_name and password:
            existing = connection.execute(
                "SELECT id FROM admins WHERE username = ?",
                (username,)
            ).fetchone()

            if not existing:
                connection.execute(
                    """
                    INSERT INTO admins
                    (username, password_hash, full_name)
                    VALUES (?, ?, ?)
                    """,
                    (
                        username,
                        generate_password_hash(password),
                        full_name
                    )
                )

    connection.commit()
    connection.close()


if __name__ == "__main__":
    initialize_database()
    print("Database initialized successfully.")
